vim.lsp.enable("lua_ls")
vim.lsp.enable("rust_analyzer")
vim.lsp.enable("ansiblels")
vim.lsp.enable("ts_ls")
vim.lsp.enable("superhtml")
vim.lsp.enable("cssls")
vim.lsp.enable("stylelint_lsp")
vim.lsp.enable("qmlls")

vim.keymap.set("n", "<leader>tih", function()
  vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
end, { desc = "Toggle inlay hints" })
